@startuml Basic tic-tac-toe
class Game {
    int currentPlayer
    int[] playerMoves
    int winner
    int[] playerWins
    Sprite player1
    Sprite player2
    Sprite GetPlayerSprite(int squareNumber)
    Sprite GetBoardBackgroundSprite()
    void PlayerMove(int squareNumber)
    int CheckForWinner(int squareNumber)
}
class Square {
    Game game
    int squareNumber
    BoxCollider2D boxCollider
    SpriteRenderer playerSprite
    void OnClick()
}
Game -- Square

@enduml